### ISSUE TITLE
PS3 controller can't pair

### ISSUE THREAD

**Issue by Lauszus** [felis/USB_Host_Shield_2.0#167]
It seems like the pull request: https://github.com/felis/USB_Host_Shield_2.0/pull/145 is causing issues for some users, as they are not able to pair with a PS3 controller.

@felis and @xxxajk can any of you comment on this? Can you guys think of a fix.

**Comment by Lauszus** [comment]
I have just sent the user an email and asked him to provide some more information of the problem.

**Comment by sanelss** [comment]
This is what happens with that commit(which fails to sync with controller):

PS3 Bluetooth Library Started
Bluetooth Dongle Initialized
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Incoming Connection Request
Remote Name: PLAYSTA


which gets stuck there and after flashing the sync lights for a little bit they all turn off.

this is what happens when you undo that commit and it successfully pairs:

Gamepad is connecting
Incoming Connection Request
Remote Name: PLAYSTA
Connected to Device: 00:23:06:11:96:5F
HID Control Incoming Connection Request
HID Control Successfully Configured
HID Interrupt Incoming Connection Request
HID Interrupt Successfully Configured
Wait For Incoming Connection Request
Dualshock 3 Controller Enabled

**Comment by xxxajk** [comment]
Yeah, so fix the toggle issue in your driver.

**Comment by Lauszus** [comment]
Sorry Andrew, but he is using my driver and it is not setting the toggle register, but is just calling the inTransfer function, so I believe it is a bug in the Usb core.

**Comment by Lauszus** [comment]
Btw @sanelss could you try to enable extra debugging as well by uncommenting this line: https://github.com/felis/USB_Host_Shield_2.0/blob/master/BTD.cpp#L20?

**Comment by sanelss** [comment]
this is advanced debug when it fails:

PS3 Bluetooth Library Started
BTD ConfigureDevice
BTD Init
Addr: 01
Endpoint descriptor:
Length:		07
Type:		05
Address:	81
Attributes:	03
MaxPktSize:	0010
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	82
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	02
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Bluetooth Dongle Initialized
Connection established
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Class of device: 00 05 08
Incoming Connection Request
Remote Name: PLAYSTA

**Comment by sanelss** [comment]
this is advance debug when it works undoing that commit:

PS3 Bluetooth Library Started
BTD ConfigureDevice
BTD Init
Addr: 01
Endpoint descriptor:
Length:		07
Type:		05
Address:	81
Attributes:	03
MaxPktSize:	0010
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	82
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	02
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Bluetooth Dongle Initialized
Connection established
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Class of device: 00 05 08
Incoming Connection Request
Remote Name: PLAYSTA
Unmanaged HCI Event: 6C
Unmanaged HCI Event: 6C
Connection established
Connected to Device: 00:23:06:11:96:5F
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
HID Control Incoming Connection Request
Connection established
Connection established
Connection established
HID Control Successfully Configured
HID Interrupt Incoming Connection Request
HID Interrupt Successfully Configured
Wait For Incoming Connection Request
Dualshock 3 Controller Enabled

Cross
Circle

**Comment by Lauszus** [comment]
When it is connected does the joysticks work?

**Comment by sanelss** [comment]
yes everything works when it connects

**Comment by xxxajk** [comment]
sanelss: can you put in a line that tells us if there is a toggle error? if there is a toggle error then the toggle was not set up correctly. (yes really). 
The commit actually is a bugfix for code bugs that used to happen a long time ago, but shouldn't happen anymore. If they are still happening then the actual driver is really at fault.

**Comment by sanelss** [comment]
"can you put in a line that tells us if there is a toggle error?"

what line where? I'm not familiar at all with the library.

**Comment by Lauszus** [comment]
Hmm for some reason the full device name is cut short. This usually means that the dongle does not support 2.0+EDR, but then the bytes that got the joystick and accelerometer data will also be cut short. Have you tried another dongle?

And yes as @xxxajk suggested please add some debug info at the line, so we can see if it and when it is run.

**Comment by Lauszus** [comment]
@sanelss after this line: https://github.com/felis/USB_Host_Shield_2.0/pull/145/files#diff-f382db0d87969c32dd22c1c4116009e1R237

**Comment by xxxajk** [comment]
Before the line that was replaced in commit #145

**Comment by xxxajk** [comment]
or after...  LOL

**Comment by sanelss** [comment]
I added this to the file:

Serial.print("Toggle bit pre command: ");
Serial.println(pep->bmRcvToggle);
//pep->bmRcvToggle = (regRd(rHRSL) & bmSNDTOGRD) ? 0 : 1;	//works
pep->bmRcvToggle = (regRd(rHRSL) & bmRCVTOGRD) ? 0 : 1;		//fails
Serial.print("Toggle bit post command: ");
Serial.println(pep->bmRcvToggle);

**Comment by sanelss** [comment]
output when it fails:


PS3 Bluetooth Library Started
BTD ConfigureDevice
BTD Init
Addr: 01
Endpoint descriptor:
Length:		07
Type:		05
Address:	81
Attributes:	03
MaxPktSize:	0010
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	82
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	02
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Bluetooth Dongle Initialized
Connection established
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Class of device: 00 05 08
Incoming Connection Request
Remote Name: PLAYSTAToggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 0
Toggle bit pre command: 0
Toggle bit post command: 1

**Comment by sanelss** [comment]
when it's trying to connect, every few seconds it would run that bit of code and the serial monitor would show an update until it eventually stops trying and the controller lights turn off

**Comment by Lauszus** [comment]
What happens if you comment out both?
```
//pep->bmRcvToggle = (regRd(rHRSL) & bmSNDTOGRD) ? 0 : 1; //works
pep->bmRcvToggle = (regRd(rHRSL) & bmRCVTOGRD) ? 0 : 1; //fails
```

**Comment by sanelss** [comment]
This is what happens when the working line is enabled:

PS3 Bluetooth Library Started
BTD ConfigureDevice
BTD Init
Addr: 01
Endpoint descriptor:
Length:		07
Type:		05
Address:	81
Attributes:	03
MaxPktSize:	0010
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	82
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	02
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Bluetooth Dongle Initialized
Connection established
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Class of device: 00 05 08
Incoming Connection Request
Remote Name: PLAYSTAToggle bit pre command: 1
Toggle bit post command: 1

Unmanaged HCI Event: 6CToggle bit pre command: 1
Toggle bit post command: 1

Unmanaged HCI Event: 6CToggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1

Connection established
Connected to Device: 00:23:06:11:96:5F
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
HID Control Incoming Connection Request
Connection established
Connection established
Connection established
HID Control Successfully Configured
HID Interrupt Incoming Connection Request
HID Interrupt Successfully Configured
Wait For Incoming Connection Request
Dualshock 3 Controller Enabled

LeftHatX: 141	LeftHatY: 122	RightHatX: 132	RightHatY: 126
LeftHatX: 141	LeftHatY: 122	RightHatX: 132	RightHatY: 126

**Comment by sanelss** [comment]
It also works when both lines are commented out:

PS3 Bluetooth Library Started
BTD ConfigureDevice
BTD Init
Addr: 01
Endpoint descriptor:
Length:		07
Type:		05
Address:	81
Attributes:	03
MaxPktSize:	0010
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	82
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	02
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Bluetooth Dongle Initialized
Connection established
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Class of device: 00 05 08
Incoming Connection Request
Remote Name: PLAYSTAToggle bit pre command: 1
Toggle bit post command: 1

Unmanaged HCI Event: 6CToggle bit pre command: 1
Toggle bit post command: 1

Unmanaged HCI Event: 6CToggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1
Toggle bit pre command: 1
Toggle bit post command: 1

Connection established
Connected to Device: 00:23:06:11:96:5F
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
HID Control Incoming Connection Request
Connection established
Connection established
Connection established
HID Control Successfully Configured
HID Interrupt Incoming Connection Request
HID Interrupt Successfully Configured
Wait For Incoming Connection Request
Dualshock 3 Controller Enabled

LeftHatX: 138	LeftHatY: 126	RightHatX: 132	RightHatY: 126
LeftHatX: 138	LeftHatY: 126	RightHatX: 132	RightHatY: 126
LeftHatX: 138	LeftHatY: 126	RightHatX: 132	RightHatY: 126

**Comment by xxxajk** [comment]
Toggle errors should not happen if toggle is correctly handled, and if the device isn't horked.
Obviously the toggle is wrong, and needs to be set. 
Where, exactly, I do not know. I don't own that controller.
That's all the advice I can offer.

**Comment by Lauszus** [comment]
Hmm can you try to add a 1 ms delay before this line: https://github.com/felis/USB_Host_Shield_2.0/blob/master/Usb.cpp#L234?

**Comment by sanelss** [comment]
adding that delay fixed the problem:

Serial.print("Toggle bit pre command: ");
Serial.println(pep->bmRcvToggle);
//pep->bmRcvToggle = (regRd(rHRSL) & bmSNDTOGRD) ? 0 : 1;	//works
pep->bmRcvToggle = (regRd(rHRSL) & bmRCVTOGRD) ? 0 : 1;		//fails
Serial.print("Toggle bit post command: ");
Serial.println(pep->bmRcvToggle);



PS3 Bluetooth Library Started
BTD ConfigureDevice
BTD Init
Addr: 01
Endpoint descriptor:
Length:		07
Type:		05
Address:	81
Attributes:	03
MaxPktSize:	0010
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	82
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Endpoint descriptor:
Length:		07
Type:		05
Address:	02
Attributes:	02
MaxPktSize:	0040
Poll Intrv:	01
Bluetooth Dongle Initialized
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1B:10:00:2A:EC
Wait For Incoming Connection Request
Gamepad is connecting
Class of device: 00 05 08
Incoming Connection Request
Remote Name: PLAYSTATION(R)3 Controller
Connection established
Connected to Device: 00:23:06:11:96:5F
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
Connection established
HID Control Incoming Connection Request
Connection established
HID Control Successfully Configured
HID Interrupt Incoming Connection Request
HID Interrupt Successfully Configured
Wait For Incoming Connection Request
Dualshock 3 Controller Enabled

LeftHatX: 139	LeftHatY: 126	RightHatX: 132	RightHatY: 125
LeftHatX: 139	LeftHatY: 126	RightHatX: 132	RightHatY: 125
LeftHatX: 139	LeftHatY: 126	RightHatX: 132	RightHatY: 125

**Comment by Lauszus** [comment]
Okay. The reason is that it is trying to read from the device to fast if we are trying to read more than the maximum bytes of the endpoint. I will work on a fix. Thanks a lot for your feedback!

**Comment by sanelss** [comment]
No problem. As noted I could run an old version but hope this will helps others who may have issues. I'm sure you'll hear from me again at a later time xD This is the third time my setup didn't get along with the current library version and needed your attention =p

**Comment by Lauszus** [comment]
Can you add the following code below this line: https://github.com/felis/USB_Host_Shield_2.0/blob/master/Usb.cpp#L283.
```C++
 else
    delayMicroseconds(1000);
```
Then lower the value until it stops working.

**Comment by Lauszus** [comment]
@xxxajk it might be better to have the inTransfer take the bInterval as an argument, so it can delay the appropriate time between transfers.

**Comment by sanelss** [comment]
300us and higher it works.
200us and lower it fails

the timing issue may be due to the fact i'm running a teensy 3.0 at a much higher clock rate than most typical arduinos.

**Comment by Lauszus** [comment]
Yes that could differently be the issue. Anyway this needs to be fixed properly. I will come up with a fix ;)

**Comment by Lauszus** [comment]
@sanelss please try: https://github.com/felis/USB_Host_Shield_2.0/pull/168.

**Comment by sanelss** [comment]
#168 fixes the issue

**Comment by Lauszus** [comment]
@sanelss thank you for your feedback. I will merge it now then!

**Comment by Lauszus** [comment]
Hmm I will wait for the Travis build to finish first ;)
