### ISSUE TITLE
Question about usb hub

### ISSUE THREAD

**Issue by ernesto-xload** [felis/USB_Host_Shield_2.0#275]
Hello, just a question:

To handle a keyboard connected to a usb hub only is needed include usbhub.h library and create the instance with: "USBHub Hub1(&Usb)" after "USB     Usb"?

Best regards and a lot of thanks in advance.

**Comment by xxxajk** [comment]
Simple answer is yes.

On Jan 5, 2017 3:04 PM, "Ernesto" <notifications@github.com> wrote:

Hello, just a question:

To handle a keyboard connected to a usb hub only is needed include usbhub.h
library and create the instance with: "USBHub Hub1(&Usb)" after "USB Usb"?

Best regards and a lot of thanks in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/felis/USB_Host_Shield_2.0/issues/275>, or mute the
thread

**Comment by Lauszus** [comment]
This is also documented in the README: https://github.com/felis/USB_Host_Shield_2.0#faq.

**Comment by sudha100** [comment]
SIR IN THE USB HUB THE USB HUB  DEVICE DETAILS ARE NOT DISPLAYED

**Comment by sudha100** [comment]
how to use USB HUB demo for connecting two or more devices with arduino.  and find the details of 

usb hub

and connected devices
