### ISSUE TITLE
Is possible two mouse display to arduino serial monitor?

### ISSUE THREAD

**Issue by JoJunYeong** [felis/USB_Host_Shield_2.0#545]
I googled everything but the creater says "I'll check" and it's end.

there is no more comment.

is this possible? to display port1 mouse, port2 mouse?

if it possible, how can I change my example code HIDBootKbdMouse.ino ?

**Comment by Lauszus** [comment]
Yes. Simply use a hub and create two `HIDBoot<USB_HID_PROTOCOL_MOUSE>` instances. You could base it on the following example: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/HID/USBHIDBootKbdAndMouse/USBHIDBootKbdAndMouse.ino, but instead of using a joystick and mouse you simply use two mice.
