### ISSUE TITLE
Shield works correctly only when Arduino connected to USB?

### ISSUE THREAD

**Issue by sybeck2k** [felis/USB_Host_Shield_2.0#764]
I've plugged a Joystick to my USB Shield and I'm using the example code HID/Joystick to have a pin go high when a button is pressed, and low when another button is pressed. The program works correctly when Arduino is plugged to my PC - but it does not work when using an external supply or power-only USB.
I've tested that:
- The while(!Serial) is not the issue (moved to a SW serial/removed the code)
- Using an Arduino Uno or Leonardo has exactly the same result
- The USB shield init completes correctly
- Other code not related to the USB Shield is working correclty (using a timer to switch on/off a led on a different pin works)

I can't see where is the relationship between having the Arduino USB connected. Any help/test/advice would be appreciated!

**Comment by xxxajk** [comment]
Are you sure that the 5v rail is actually providing 5v under load? if not, the then regulator is to blame. 
The work-around is to use a powered hub, or, to supply 5v separately. 
At a minimum you need to supply 500mA to be within spec on USB, your PC is probably supplying 1000mA, which bypasses the on-board regulator for 5v. What you can do is have a 1000mA (or more) 5v supply and attach it to the 5v pins on the Arduino, and not hook up any other power or USB connection. Don't use the power in, since that will go through the weak 5v regulator, and see if that makes it work.
