### ISSUE TITLE
Help with RTL8153 Gigabit Ethernet Adapter on Arduino

### ISSUE THREAD

**Issue by Miguel0101** [felis/USB_Host_Shield_2.0#778]
I have a USB network adapter (Vendor ID: 0x0BDA, Product ID: 0x8153). So I need help dealing with this network adapter. Can someone help me? I thank.

Using an Arduino Uno.

**Comment by xxxajk** [comment]
totally not going to happen on an UNO, not enough RAM. Perhaps UNO R4, though, but then, you would want to move to UHS30 which is going to be easier to manage, and requires more RAM too. Generally I avoid any MCU with less than 64K RAM and 8 bit anymore, since newer offerings do more for less money.

**Comment by Miguel0101** [comment]
> totally not going to happen on an UNO, not enough RAM. Perhaps UNO R4, though, but then, you would want to move to UHS30 which is going to be easier to manage, and requires more RAM too. Generally I avoid any MCU with less than 64K RAM and 8 bit anymore, since newer offerings do more for less money.

Thanks for your response!

I have a ESP32 Wrover with 8MB of flash and 8MB of RAM(PSRAM).
It should probably work for its processing power and memory.
